from dataclasses import dataclass, field
from typing import Optional, Dict, List, Any

# Day 5-7: Design Data Models

@dataclass
class RawTransaction:
    """
    Represents the structure of a raw transaction log as generated.
    This is the input for Agent 1.
    """
    transaction_id: str
    pan: str
    cardholder_name: str
    transaction_amount: float
    merchant_details: str
    timestamp: str
    location_data: Dict[str, str]
    # PCI-DSS violation if present
    cvv: Optional[str] = None
    # Annotation from the generator for testing purposes
    suspicion_reason: Optional[str] = None

@dataclass
class SanitizedTransaction:
    """
    Represents a transaction after being processed by Agent 1 (Sanitizer).
    PAN is masked and sensitive PII is removed. This is the input for Agent 2.
    """
    transaction_id: str
    # PAN will be masked (e.g., "4111-XXXX-XXXX-1111")
    pan: str
    # Cardholder name can be considered PII, so it's removed or anonymized.
    # For this model, we will remove it.
    transaction_amount: float
    merchant_details: str
    timestamp: str
    location_data: Dict[str, str]
    # Flag to indicate if a PCI violation was detected and fixed.
    compliance_issues_detected: List[str] = field(default_factory=list)


@dataclass
class AnalyzedTransaction:
    """
    Represents a transaction after being processed by Agent 2 (Risk Analyzer).
    Includes risk scoring and analysis. This is the input for Agent 3.
    """
    sanitized_data: SanitizedTransaction
    risk_score: float  # e.g., 0.0 to 1.0
    risk_level: str  # e.g., "Low", "Medium", "High", "Critical"
    risk_reasons: List[str] = field(default_factory=list)


@dataclass
class FinalReport:
    """
    Represents the final human-readable report generated by Agent 3.
    """
    transaction_id: str
    timestamp: str
    is_compliant: bool
    compliance_summary: str
    risk_assessment: str
    overall_summary: str


if __name__ == '__main__':
    # This is a simple demonstration of how the models could be used.
    
    # 1. A raw log comes in
    raw_tx = RawTransaction(
        transaction_id="abc-123",
        pan="4111222233334444",
        cardholder_name="John Doe",
        transaction_amount=150.75,
        merchant_details="Test Merchant",
        timestamp= "2026-01-28T10:00:00Z",
        location_data={"city": "New York", "country": "USA"},
        cvv="123" # Violation!
    )
    print("--- Raw Transaction ---")
    print(raw_tx)

    # 2. Agent 1 sanitizes it
    sanitized_tx = SanitizedTransaction(
        transaction_id=raw_tx.transaction_id,
        pan="4111-XXXX-XXXX-4444", # Masked PAN
        transaction_amount=raw_tx.transaction_amount,
        merchant_details=raw_tx.merchant_details,
        timestamp=raw_tx.timestamp,
        location_data=raw_tx.location_data,
        compliance_issues_detected=["CVV was present and has been removed."]
    )
    print("\n--- Sanitized Transaction (from Agent 1) ---")
    print(sanitized_tx)

    # 3. Agent 2 analyzes it for risk
    analyzed_tx = AnalyzedTransaction(
        sanitized_data=sanitized_tx,
        risk_score=0.8,
        risk_level="High",
        risk_reasons=["Transaction amount is higher than average for this merchant."]
    )
    print("\n--- Analyzed Transaction (from Agent 2) ---")
    print(analyzed_tx)

    # 4. Agent 3 generates a final report
    final_report = FinalReport(
        transaction_id=analyzed_tx.sanitized_data.transaction_id,
        timestamp=analyzed_tx.sanitized_data.timestamp,
        is_compliant=False,
        compliance_summary="A PCI-DSS violation was detected: CVV was stored with the transaction. The data has been sanitized.",
        risk_assessment="High Risk: The transaction amount was flagged as unusually high.",
        overall_summary="This transaction presented a high risk and contained a compliance violation. Review immediately."
    )
    print("\n--- Final Report (from Agent 3) ---")
    print(final_report)
